# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/antchfx/htmlquery";
    fetch = {
      type = "git";
      url = "https://github.com/antchfx/htmlquery";
      rev = "496e959f9577cce9b1723e92628f801394545b28";
      sha256 = "0hb0xdlzyz65xf10wykqdpzn33kawc15sbvyggnnzlbfga8i65xk";
    };
  }
  {
    goPackagePath = "github.com/antchfx/jsonquery";
    fetch = {
      type = "git";
      url = "https://github.com/antchfx/jsonquery";
      rev = "b8565c15b0757d4d4fbbeddba11d627a1ba08e62";
      sha256 = "0w8p8rxikg4vqn7ma7sacznzmfdlwhgkpjb45m7384bfyvnf22kl";
    };
  }
  {
    goPackagePath = "github.com/antchfx/xpath";
    fetch = {
      type = "git";
      url = "https://github.com/antchfx/xpath";
      rev = "a5d9242ed21be6cae3717a1b422cfc1e7a1ce7d6";
      sha256 = "0gd5b0nav6ir6386nxz7i7zhbn7qdm9avd9477xxj99pqbzbgpm6";
    };
  }
  {
    goPackagePath = "github.com/disintegration/imaging";
    fetch = {
      type = "git";
      url = "https://github.com/disintegration/imaging";
      rev = "339f5d48a4f3352fe8bcdefe81de01e25f711b09";
      sha256 = "0hv0bf37ljinn880bn5kbvlgsghjdvnzk913q8h63lzi2pydvhl2";
    };
  }
  {
    goPackagePath = "github.com/godbus/dbus";
    fetch = {
      type = "git";
      url = "https://github.com/godbus/dbus";
      rev = "9eb6257e13ab38178e97d1f28cf5b444d035235a";
      sha256 = "02w9ky3pp3z4fmhyh1w2pkg9da377yg9fbaaa79zpw1vdsv8x306";
    };
  }
  {
    goPackagePath = "github.com/golang/groupcache";
    fetch = {
      type = "git";
      url = "https://github.com/golang/groupcache";
      rev = "8c9f03a8e57eb486e42badaed3fb287da51807ba";
      sha256 = "0vjjr79r32icjzlb05wn02k59av7jx0rn1jijml8r4whlg7dnkfh";
    };
  }
  {
    goPackagePath = "github.com/lestrrat-go/strftime";
    fetch = {
      type = "git";
      url = "https://github.com/lestrrat-go/strftime";
      rev = "3a6bf1db28c7b5d5e602bbc73b08211291bc55d1";
      sha256 = "09rcn2by0xh148n7mw6df3g4gl6nzf5c54313z3fiydcrf8wk78g";
    };
  }
  {
    goPackagePath = "github.com/nfnt/resize";
    fetch = {
      type = "git";
      url = "https://github.com/nfnt/resize";
      rev = "83c6a9932646f83e3267f353373d47347b6036b2";
      sha256 = "005cpiwq28krbjf0zjwpfh63rp4s4is58700idn24fs3g7wdbwya";
    };
  }
  {
    goPackagePath = "github.com/pkg/errors";
    fetch = {
      type = "git";
      url = "https://github.com/pkg/errors";
      rev = "614d223910a179a466c1767a985424175c39b465";
      sha256 = "1761pybhc2kqr6v5fm8faj08x9bql8427yqg6vnfv6nhrasx1mwq";
    };
  }
  {
    goPackagePath = "golang.org/x/image";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/image";
      rev = "e162460cd6b5176292c0a160614547bab9a90788";
      sha256 = "0ng3jb75ca7gqz6x4dyd4r722zqg7xxj110c3ii9abikc4l8mjc3";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "ff519b6c91021e6316e1df005bc19f266994ddda";
      sha256 = "162ssgcc0kgj42ajaki0q3j5lwmixqqwkdqcmz41xg1k8wjm7riw";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "22f1617af38ed4cd65b3b96e02bab267e560155c";
      sha256 = "11jdvix83xcl5xnb039y4zrz4x5skzsps0w1jryp6wrar53cydvz";
    };
  }
]
